# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 03:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('create_datetime', models.DateTimeField()),
                ('update_datetime', models.DateTimeField()),
            ],
        ),
    ]
